### ISSUE TITLE
Error 500 for invalid requests

### ISSUE THREAD

**Issue by GityaMan** [Baldinof/roadrunner-bundle#151]
https://github.com/Baldinof/roadrunner-bundle/blob/afa9d2319de350bfad6d63520b58430747273e02/src/RoadRunnerBridge/HttpFoundationWorker.php#L99C24-L99C33

The problem is on the client side, but instead of 400 response code we get 500 response.

**Comment by Baldinof** [comment]
Hello, can you share an example request that would trigger this exception?

**Comment by GityaMan** [comment]
Hello, unfortunately I can't find the problematic request in the logs.

It seems that this is not even a user request issue, as I initially thought. It's a problem with the roadrunner communication with the workers.

Is it possible to add the problematic URL itself to the exception to find it in the logs?

`Exception: Failed to parse RoadRunner request URI in /var/www/vendor/baldinof/roadrunner-bundle/src/RoadRunnerBridge/HttpFoundationWorker.php:99
Stack trace:
#0 /var/www/vendor/baldinof/roadrunner-bundle/src/RoadRunnerBridge/HttpFoundationWorker.php(73): Baldinof\RoadRunnerBundle\RoadRunnerBridge\HttpFoundationWorker->configureServer(Object(Spiral\RoadRunner\Http\Request))
#1 /var/www/vendor/baldinof/roadrunner-bundle/src/RoadRunnerBridge/HttpFoundationWorker.php(35): Baldinof\RoadRunnerBundle\RoadRunnerBridge\HttpFoundationWorker->toSymfonyRequest(Object(Spiral\RoadRunner\Http\Request))
#2 /var/www/vendor/baldinof/roadrunner-bundle/src/Worker/HttpWorker.php(93): Baldinof\RoadRunnerBundle\RoadRunnerBridge\HttpFoundationWorker->waitRequest()
#3 /var/www/vendor/baldinof/roadrunner-bundle/src/Runtime/Runner.php(33): Baldinof\RoadRunnerBundle\Worker\HttpWorker->start()
#4 /var/www/vendor/autoload_runtime.php(29): Baldinof\RoadRunnerBundle\Runtime\Runner->run()
#5 /var/www/public/index.php(5): require_once('/var/www/vendor...')
#6 {main}`

`RoadRunner can't communicate with the worker	{"reason": "worker hung or process was killed", "pid": 26, "internal_event_name": "EventWorkerError", "error": "sync_worker_receive_frame: Network: EOF"}`

`{"L":"ERROR","T":"2024-12-12T04:24:22+0000","N":"http        ","M":"execute","start":"2024-12-12T04:24:22+0000","elapsed":51,"error":"sync_worker_receive_frame: Network: EOF"}`
